version: "3.8"

services:
  web:
    image: odoo:18.0
    container_name: odoo18
    depends_on:
      - db
    ports:
      - "8070:8069"
    volumes:
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
 
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: odoo --dev xml -c /etc/odoo/odoo.conf
    restart: always
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: odoo18-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5301:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

volumes:
  odoo-db-data:
